path_to_source: "" #full_path_to_folder_with_howitzer_project"
link_to_web_repository: "" #link_to_web_folder_with_howitzer_project"
web_repository: github

# -- Capistrano settings
application: howitzer_stat
domain: localhost
user: deployer
deploy_to: /var/www/${application}

# -- Unicorn settings
worker_processes: 2
port: 80